### ISSUE TITLE
/api/movies error 500

### ISSUE THREAD

**Issue by kirayatail** [cthdidIT/itbio#3]
```
exception: "#<NoMethodError: undefined method `split' for :"user-agent":Symbol>"

0: {id: 16, trace: "app/models/movie.rb:85:in 'download_data'"}
1: {id: 17, trace: "app/models/movie.rb:81:in 'request'"}
2: {id: 18, trace: "app/models/movie.rb:68:in 'current'"}
3: {id: 19, trace: "app/controllers/movies_controller.rb:6:in 'index'"}
```

**Comment by Edholm** [comment]
This is probably not an issue anymore since I can't seem to reproduce it. @kirayatail can you test when you get the time?
